### ISSUE TITLE
resource not accessible by integration

### ISSUE THREAD

**Issue by yalattas** [keepbang/bump-tag-version#1]
I am using this action and another action but failing for both. So I think my problem with the token perhaps
```
- name: Bump tag version
        if: github.ref == 'refs/heads/main'
        id: tag
        uses: keepbang/bump-tag-version@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
```

I haven't created secrets.GITHUB_TOKEN or modify anything and organization is relatively new.

I was having only 1 tag on main branch which is `v0.0.0` then I tested `v1.0.0` and `v1.0.1` but all are failing

Possibly the reason behind the failure ?

**Comment by yalattas** [comment]
resolved by adding
```
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
```
